'use strict';

/**
 * Generates cryptographically strong secrets for local development.
 *
 * Usage: npm run secrets:generate
 *
 * These values are for development only. In production, secrets belong in the
 * platform's secret manager (Google Secret Manager, AWS SSM, Vault) — never in
 * the repository, never in a .env file that is committed, and never in shell
 * history.
 */

const crypto = require('crypto');

const secrets = {
  JWT_SECRET: crypto.randomBytes(48).toString('base64'),
  PII_ENCRYPTION_KEY: crypto.randomBytes(32).toString('hex'),
  BLIND_INDEX_KEY: crypto.randomBytes(48).toString('base64'),
};

const lines = [
  '# Generated by `npm run secrets:generate`',
  '# Development only — rotate before any real deployment.',
  `NODE_ENV=development`,
  `PORT=5000`,
  '',
  ...Object.entries(secrets).map(([k, v]) => `${k}=${v}`),
  '',
  '# Postgres',
  'PGHOST=localhost',
  'PGPORT=5432',
  'PGDATABASE=tracalorie',
  'PGUSER=postgres',
  'PGPASSWORD=tracalorie_dev_password',
  '',
  '# Comma-separated origin allowlist. Required in production.',
  'CORS_ORIGINS=http://localhost:3000',
  '',
  '# Google Cloud Storage export bucket (optional).',
  '# GCS_EXPORT_BUCKET=my-tracalorie-exports',
  '# GCS_CLIENT_EMAIL=tracalorie-exports@my-project.iam.gserviceaccount.com',
  '# GCS_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\\n...\\n-----END PRIVATE KEY-----\\n"',
];

process.stdout.write(`${lines.join('\n')}\n`);
